# Usamos una imagen de Java con JDK 17
FROM openjdk:17-jdk-slim

# Establecemos el directorio de trabajo
WORKDIR /app

# Copiamos el archivo JAR del backend
COPY target/andaluciaskills-0.0.1-SNAPSHOT.jar app.jar

# Exponemos el puerto 8080
EXPOSE 8080

# Comando para ejecutar el backend
ENTRYPOINT ["java", "-jar", "app.jar"]
